### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by obartra** [jonathantneal/postcss-partial-import#40]
When migrating [postcss-loader](https://github.com/postcss/postcss-loader) from `1.3.3` to `2.0.0` I get the following error (Node 7.9.0):

```bash
Node#before is deprecated. Use Node#raws.before
(node:50262) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'parent' of undefined
(node:50262) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:50262) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot set property 'parent' of undefined
```
Which is a particularly useless message from Node. If I run instead: `node --trace-warnings node_modules/.bin/webpack --config webpack.config.js` I get:

```
(node:50319) TypeError: Cannot set property 'parent' of undefined
    at Root.removeChild ([project]/node_modules/postcss/lib/container.es6:442:9)
    at Root.removeChild ([project]/node_modules/postcss/lib/root.es6:29:16)
    at [project]/node_modules/postcss-loader/node_modules/postcss/lib/container.es6:611:38
    at Array.map (native)
    at Root.normalize ([project]/node_modules/postcss-loader/node_modules/postcss/lib/container.es6:608:31)
    at Root.normalize ([project]/node_modules/postcss-loader/node_modules/postcss/lib/root.es6:32:21)
    at Root.insertBefore ([project]/node_modules/postcss-loader/node_modules/postcss/lib/container.es6:375:26)
    at AtRule.replaceWith ([project]/node_modules/postcss-loader/node_modules/postcss/lib/node.es6:232:29)
    at [project]/node_modules/postcss-partial-import/index.js:109:21
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
Node#moveAfter was deprecated. Use Node#after.
```

This persists on the latest version (`2.0.5`) of postcss-loader.

Filing it here as per [michael-ciniawsky](https://github.com/postcss/postcss-loader/issues/231#issuecomment-300661974)'s suggestion since the stack trace suggests an issue with postcss-partial-import

**Comment by jonathantneal** [comment]
I updated to postcss-import 9.1.0 which may resolve this issue. Would you try again?

**Comment by obartra** [comment]
It's working great! Thanks!
